#!/bin/bash

# Step 1: Install Docker
sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

# Auto-press [ENTER] for repository prompt
echo | sudo tee /etc/apt/sources.list.d/docker.list

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update
sudo apt install -y docker-ce

# Step 2: Execute Docker command without sudo
sudo usermod -aG docker ${USER}
su - ${USER}
sudo usermod -aG docker ${USER}


echo "Docker installation and configuration completed."
